"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _dashboard from './dashboard.bones.json'

registerBones({
  "dashboard": _dashboard,
})
